# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2904cd32593bfc247e5c3a86f9bf2b27d5acd0f87904d077eb3675ba62c36078ee1cb1208320fe5a67c9a748a2cc8c1fa06dc000a4c90416f6fa4ce5dd1912fc

test:
  secret_key_base: 4541211ee590c3ea7579f9b9aa3ae3bde27a2b122e5ce7d8176373291a15e3890dfe70e06c2860f07b090abc27c36b1ea170abac1b40f553ae5b46ed3d72ebd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
